### ISSUE TITLE
KeyError: 'text'

### ISSUE THREAD

**Issue by AtharvaSolanki** [BrasD99/HeyGenClone#13]
Traceback (most recent call last):
  File "/home/bhits-003/xcelore/Gen Ai Audio/hey_gen/HeyGenClone-main/speech_changer.py", line 66, in <module>
    update_voice(
  File "/home/bhits-003/xcelore/Gen Ai Audio/hey_gen/HeyGenClone-main/speech_changer.py", line 47, in update_voice
    temp_result_avi = to_avi(frames, orig_clip.fps)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bhits-003/xcelore/Gen Ai Audio/hey_gen/HeyGenClone-main/core/helpers.py", line 61, in to_avi
    if frame['text']:
       ~~~~~^^^^^^^^
i am getting this error when i use voice changer

**Comment by AtharvaSolanki** [comment]
File "/home/bhits-003/xcelore/Gen Ai Audio/hey_gen/HeyGenClone-main/speech_changer.py", line 66, in <module>
    update_voice(
  File "/home/bhits-003/xcelore/Gen Ai Audio/hey_gen/HeyGenClone-main/speech_changer.py", line 46, in update_voice
    frames = lip_sync.sync(frames, voice_filename, orig_clip.fps)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: LipSync.sync() missing 1 required positional argument: 'use_enhancer'
