### ISSUE TITLE
TypeError: LipSync.sync() missing 1 required positional argument: 'use_enhancer'

### ISSUE THREAD

**Issue by pengchanglu** [BrasD99/HeyGenClone#20]
**python -V  
python 3.10.10**

 python speech_changer.py 2.wav els.mp4 -o out.mp4
E:\Program\python\python3.10.10\lib\site-packages\torchvision\transforms\functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
onnx load done
Processing: 100%|▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒| 1/1 [00:28<00:00, 28.53s/it]
Processing frames: 93it [00:12,  7.70it/s]
Traceback (most recent call last):
  File "E:\git\HeyGen\HeyGenClone\speech_changer.py", line 66, in <module>
    update_voice(
  File "E:\git\HeyGen\HeyGenClone\speech_changer.py", line 46, in update_voice
    frames = lip_sync.sync(frames, voice_filename, orig_clip.fps)
TypeError: LipSync.sync() missing 1 required positional argument: 'use_enhancer'

![image](https://github.com/BrasD99/HeyGenClone/assets/29162748/9e034ebd-5ed7-4439-9873-5bee97912f81)

**Comment by brunoreisportela** [comment]
Does someone know how to fix this? I am having the same here. I just added True there to make it pass, but I don't know what is the proper flag in this case.

**Comment by pedronesasas** [comment]
The same here, anybody solved the problem?

**Comment by cungur0223** [comment]
+1

**Comment by cungur0223** [comment]
line 46 in speech_charger.py
`#frames = lip_sync.sync(frames, voice_filename, orig_clip.fps)`
`frames = lip_sync.sync(frames, voice_filename, orig_clip.fps, True)`
