### ISSUE TITLE
TypeError: TranscriptionOptions.__new__() missing 1 required positional argument: 'hotwords'

### ISSUE THREAD

**Issue by cungur0223** [BrasD99/HeyGenClone#27]
After download the [model.bin] I get following error:

> tts_models/multilingual/multi-dataset/xtts_v2 is already downloaded.
 > Using model: xtts
model.bin: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.09G/3.09G [07:56<00:00, 6.47MB/s]
Traceback (most recent call last):
  File "/Users/ycj/PycharmProjects/HeyGenClone-main/translate.py", line 26, in <module>
    translate(
  File "/Users/ycj/PycharmProjects/HeyGenClone-main/translate.py", line 11, in translate
    engine = Engine(config, output_language)
  File "/Users/ycj/PycharmProjects/HeyGenClone-main/core/engine.py", line 41, in __init__
    self.whisper = load_model(
  File "/Users/ycj/PycharmProjects/HeyGenClone-main/core/whisperx/asr.py", line 100, in load_model
    default_asr_options = faster_whisper.transcribe.TranscriptionOptions(
TypeError: TranscriptionOptions.__new__() missing 1 required positional argument: 'hotwords'

**Comment by cungur0223** [comment]
fixed.

file 'core/whisperx/asr.py' line 91,
add this one line:
`'hotwords': None` 

refer to [https://github.com/SYSTRAN/faster-whisper/blob/master/faster_whisper/transcribe.py](url)
