### ISSUE TITLE
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

### ISSUE THREAD

**Issue by stakeswky** [BrasD99/HeyGenClone#3]
Hi, I ran the program successfully according to the tutorial, but it has the following problem:
Traceback (most recent call last):
  File "/root/autodl-tmp/HeyGenClone/translate.py", line 44, in <module>
    translate(
  File "/root/autodl-tmp/HeyGenClone/translate.py", line 34, in translate
    engine(video_filename, output_filename)
  File "/root/autodl-tmp/HeyGenClone/core/engine.py", line 50, in __call__
    dereverb_out = self.dereverb.split(original_audio_file)
  File "/root/autodl-tmp/HeyGenClone/core/dereverb.py", line 225, in split
    return self.pred.prediction(input)
  File "/root/autodl-tmp/HeyGenClone/core/dereverb.py", line 194, in prediction
    sources = self.demix(mix.T)
  File "/root/autodl-tmp/HeyGenClone/core/dereverb.py", line 122, in demix
    sources = self.demix_base(segmented_mix, margin_size=margin)
  File "/root/autodl-tmp/HeyGenClone/core/dereverb.py", line 156, in demix_base
    input_data_1 = -spek.cuda().numpy() if self.device.type == 'cuda' else -spek.cpu().numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

My environmental information is below:
Ubuntu 20.04
python 3.9
nvidia 3080

**Comment by BrasD99** [comment]
Ill check this out. Thanks for your issue.

**Comment by BrasD99** [comment]
Fixed in [commit](https://github.com/BrasD99/HeyGenClone/commit/9ea0c720f8ab587c3d47bff3f6919426d034d259)
